# Generated by Django 5.1.2 on 2024-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('ate_1000', 'Até 1.000'), ('1000_2000', 'De 1.000 a 2.000'), ('2000_3000', 'De 2.000 a 3.000'), ('acima_3000', 'Acima de 3.000')], default='ate_1000', max_length=15)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Ensino Superior'), ('pos', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], default='medio', max_length=15)),
            ],
        ),
    ]
