# Generated by Django 5.1.2 on 2024-10-23 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_vaga_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacoesVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('candidatos', models.ManyToManyField(related_name='vagas_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='usuarios.vaga')),
            ],
        ),
    ]
