# Generated by Django 5.1.2 on 2024-10-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_aplicacoesvaga_candidatos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacoesvaga',
            name='pretensao_salarial',
            field=models.FloatField(null=True),
        ),
    ]
